repos:
  - repo: local
    hooks:
      - id: secret-scanner
        name: Security Secret Scanner
        entry: python git_hook.py
        language: python
        stages: [commit]
        always_run: true
        pass_filenames: false
