import os
import sys
import stat
from pathlib import Path
from logger import logger

def install_hook() -> bool:
    """Installs the pre-commit git hook to .git/hooks/pre-commit."""
    git_dir = Path(".git")
    if not git_dir.exists() or not git_dir.is_dir():
        print("Error: .git directory not found. Are you in the root of a Git repository?")
        logger.error(".git folder not found during hook installation.")
        return False

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(exist_ok=True)
    
    hook_path = hooks_dir / "pre-commit"
    
    hook_content = """#!/bin/sh
# Secret Scanner Pre-Commit Hook
# Auto-generated by install_hook.py

python git_hook.py
"""
    
    try:
        with open(hook_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(hook_content)
        
        # Make the file executable
        st = os.stat(hook_path)
        os.chmod(hook_path, st.st_mode | stat.S_IEXEC | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        
        print(f"Success: Pre-commit hook installed successfully at {hook_path}")
        logger.info(f"Pre-commit hook installed at {hook_path}")
        return True
    except Exception as e:
        print(f"Error: Failed to install git hook: {e}")
        logger.error(f"Failed to install git hook: {e}")
        return False

if __name__ == "__main__":
    success = install_hook()
    sys.exit(0 if success else 1)
